name: Test Coverage

on: 
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}  
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - run: npm install
      
      - name: Create custom_art.json
        run: echo "{}" > Storage/custom_art.json

      - name: Copy example_config.js to config.js
        run: cp Storage/example_config.js Storage/config.js

      - name: Check if movieApiKey is set
        run: |
          if [ -z "${MOVIEAPIKEY}" ]; then
            echo "Error: MOVIEAPIKEY is not set." >&2
            exit 1
          fi
        env:
          MOVIEAPIKEY: ${{ secrets.MOVIEAPIKEY }}

      - name: Set movieApiKey in config.js
        run: sed -i 's/const movieApiKey = "";/const movieApiKey = "'"${{ secrets.MOVIEAPIKEY }}"'";/g' Storage/config.js
        env:
          MOVIEAPIKEY: ${{ secrets.MOVIEAPIKEY }}
      
      - run: npm run coverage
        env:
          CI: true
          
      - name: Delete custom_art.json
        run: rm Storage/custom_art.json
      
      - name: Delete config.js
        run: rm Storage/config.js
