name: Test Coverage

on: 
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}  
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Create custom_art.json
        run: echo "{}" > custom_art.json
      - run: npm run coverage
        env:
          CI: true
      - name: Delete custom_art.json
        run: rm custom_art.json
 