name: Deploy Documentation

on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' 

    - name: Install dependencies
      run: npm install

    - name: Build documentation
      run: npm run docs:build

    - name: Deploy to GitHub Pages
      run: |
        cd docs/.vuepress/dist
        git init
        git add -A
        git commit -m 'deploy'
        git push -f git@github.com:vlc-rpc/vlc-discord-rpc.git master:gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
